test_crud/config/routes.rb
# -*- encoding : utf-8 -*-
#require 'sidekiq/web'
#mount Sidekiq::Web, at: '/sidekiq'

Gshop::Application.routes.draw do

    ############################################################
  # for admin
  ############################################################
  constraints(Subdomain) do

    match 'admin', :to => redirect('/admin/reports/dashboard')

    namespace :admin do

      scope '/product' do
        # test
        resources :test_brands do
          collection do
            get :code_list
          end
        end
      end


      
  root :to => 'main#index'
  get '/clear', :to => 'main#index_clear', :as => 'root_clear'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

test_crud/app/models/test_brand.rb
# -*- encoding : utf-8 -*-
class TestBrand < ActiveRecord::Base
  # attr_accessible :title, :body
  has_one :description, :as => :model, :class_name => 'TextContent', :conditions => { :tag => TextContent::TAG_TEST_BRAND_DESCRIPTION }, :dependent => :destroy
  accepts_nested_attributes_for :description, :allow_destroy => true

  has_one :img_representative, :as => :attachable, :class_name => '::ImageFileRepresentative', :conditions => { :tag => ::ImageFileRepresentative::TAG_TEST_BRAND_REPRESENTATIVE }, :dependent => :destroy
  accepts_nested_attributes_for :img_representative, :allow_destroy => true

end

test_crud/app/controllers/admin/test_brands_controller.rb
# -*- encoding : utf-8 -*-
class Admin::TestBrandsController < Admin::BaseController
  before_filter :admin_required

  def index
    @test_brands = TestBrand.order("test_brands.id desc").paginate(:per_page => 20, :page => params[:page])
    @test_brands = @test_brands.where('test_brands.code = ?', params[:search_code]) unless params[:search_code].blank?
    @test_brands = @test_brands.where('test_brands.name like ?', '%' + params[:search_name] + '%') unless params[:search_name].blank?
    @test_brands = @test_brands.where('test_brands.korea_name like ?', '%' + params[:search_korea_name] + '%') unless params[:search_korea_name].blank?
    # 라인업 존재여부 검색
    unless params[:search_line_up].blank?
      @test_brands = params[:search_line_up] == "1" ? @test_brands.where('test_brands.linup_count > 0') : @test_brands.where('test_brands.linup_count = 0')
    end
    # 생성일자 검색
    @test_brands = @test_brands.where("Date_format(test_brands.created_at, '%Y%m%d') >= ?", params[:created_at_start].gsub('-', '')) unless params[:created_at_start].blank?
    @test_brands = @test_brands.where("Date_format(test_brands.created_at, '%Y%m%d') <= ?", params[:created_at_end].gsub('-', '')) unless params[:created_at_end].blank?

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def new
    @test_brand = TestBrand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @test_brand }
    end
  end

  def edit
    @test_brand = TestBrand.find(params[:id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @test_brand }
    end
  end

  def create
    @test_brand = TestBrand.new(params[:test_brand])

    respond_to do |format|
      if @test_brand.save
        format.html { redirect_to admin_test_brands_path, notice: 'TestBrand was successfully created.' }
        format.json { render json: @test_brand, status: :created, location: @test_brand }
      else
        format.html { render action: "new" }
        format.json { render json: @test_brand.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    @test_brand = TestBrand.find(params[:id])

    respond_to do |format|
      if @test_brand.update_attributes(params[:test_brand])
        format.html { redirect_to admin_test_brands_path, :notice => 'Test Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @test_brand.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @test_brand = TestBrand.find(params[:id])
    @test_brand.destroy

    respond_to do |format|
      format.html { redirect_to admin_test_brands_path, :notice => 'Test Brand was deleted.' }
      format.json { head :no_content }
    end
  end
  # 중복코드 체크
  def code_list
    #/admin/product/test_brand/code_list.json?&code=112
    #remove_space 를 처리해서 검색 할때도 띄워쓰기 지워서 검색
    code = params[:code].gsub(" ","").strip
    exact = params[:exact]
    serch_id = params[:serch_id]  # 파트너 SKU 중복 조회 시 상품메타 아이디를 조회
    result = {}
    @code_list = TestBrand.select("code")
    #unless code.blank? #완전일치 또는 like 검색
    unless code.to_s.length == 0
      @code_list = (exact == 'y') ? @code_list.where("test_brands.code = ?", code.to_s) : @code_list.where("test_brands.code like ?", '%' + code.to_s + '%')
    end

    code_list = (@code_list.map &:code).as_json
    #code_list = (TestBrand.select("code").map &:code).as_json
    render :json => code_list.map { |code| code }
  end
end

test_crud/app/views/admin/test_brands/_breadcrumb.html.erb
<ul class="breadcrumb">
  <li><a href="<%=admin_test_brands_path%>">테스트 브랜드</a> </li>
  <li class="active"><%= params[:action].capitalize.to_s %></li>
</ul>

<div class="page-header">
  <h1><%= params[:action].capitalize.to_s %> <small>Test Brands</small></h1>
</div>

test_crud/app/views/admin/test_brands/_form.html.erb
<% content_for :end_of_body do %>
  <script type="text/javascript">
  $(document).ready(function(){
      //code 입력 후 중복 여부 검증
      $('#search-code').click(function(){
          var code = $('#test_brand_code').val();

          //exact=y 가 있을 경우 완전 일치 검색
          $.get("/admin/product/test_brands/code_list.json?exact=y&code=" + encodeURIComponent(code), function(data) {
              str = data;
              if (str.length==0) {
                  str='사용가능한 코드';
              } else {
                  str='이미 존재하는 코드입니다.';
              }
              $('#search-code-result').html(str);
          });
          return false;
      });
      //엔터 쳤을 때 위의 code 중복 여부 검증 실행
      $('#test_brand_code').keypress(function(e) {
          if(e.keyCode == 13) {
              $('#search-code').trigger('click');
          }
      });
  });
  </script>
<% end %>

  <%= nested_form_for([:admin, @test_brand], html: { name: "form_test_brand", class: "form-horizontal" }) do |f| %>
  <%= render :partial => 'shared/error', :locals => { :obj => @test_brand } %>
    <div class="form-group">
      <%= f.label :code, '브랜드코드', class: "control-label" %>
      <div class="controls">
        <%= f.text_field :code %><a href="#" class="btn btn-default btn-sm" id="search-code">검색</a>
        <p class="help-block">브랜드 코드는 중복될 수 없습니다. &nbsp;&nbsp;&nbsp;<span id="search-code-result" style="color: red;"></span></p>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :name, '브랜드명', class: "control-label" %>
      <div class="controls">
        <%= f.text_field   :name %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :korea_name, '브랜드한글명', class: "control-label" %>
      <div class="controls">
        <%= f.text_field   :korea_name %>
      </div>
    </div>
     <div class="form-group">
      <%= f.label :linup_count, '라인업 수', class: "control-label" %>
      <div class="controls">
        <%= f.number_field :linup_count %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :country, '지역', class: "control-label" %>
      <div class="controls">
        <%= f.text_field   :country %>
      </div>
    </div>
    <!-- image upload-->
    <%= f.fields_for :img_representative, f.object.img_representative || f.object.build_img_representative do |attachment_files_form| %>
      <div class="form-group">
        <%= attachment_files_form.label :filename, raw("브랜드 이미지"), class: 'control-label' %>

        <div class="controls">
          <%= attachment_files_form.file_field :filename, :class => "file-uploader", :data => {option:"single", btn:"btn btn-default btn-xs btn-primary", text: "파일추가"}%>

          <% unless @test_brand.img_representative.new_record? %>
            <p class="help-block">
              <%= image_tag(@test_brand.img_representative.filename.thumb_235, :alt => @test_brand.name) %></p>
            <%= attachment_files_form.check_box :_destroy, :style => "margin-top:-2px;" %>
            <%= attachment_files_form.label :_destroy, "삭제" %>
          <% end %>
        </div>
      </div>
    <% end %>
    <!-- description -->
    <%= f.fields_for :description, f.object.description || f.object.build_description do |description_form| %>
      <div class="form-group">
        <%= description_form.label :description, '설명', class: 'control-label' %>
        <div class="controls" style="margin-top:4px;">
          <%= description_form.cktext_area :content %>
        </div>
      </div>
    <% end %>

  <div class="form-actions">
    <%= f.submit :class => "btn btn-primary" %>
    <%= link_to 'Back', admin_test_brands_path, :class => 'btn btn-inverse' %>
  </div>
<% end %>

test_crud/app/views/admin/test_brands/edit.html.erb
<%= render :partial => 'breadcrumb' %>
<%= render :partial => 'form' %>

test_crud/app/views/admin/test_brands/index.html.erb
<%= render :partial => 'breadcrumb' %>
<% content_for :end_of_body do %>
  <script type="text/javascript">
      $(document).ready(function() {
      });
  </script>
<% end %>

<%= form_tag admin_test_brands_path, :method => :post, :class => 'well form-search' do %>
  <%= text_field_tag :search_code, params[:search_code], :placeholder => '브랜드코드', :class => 'input-medium' %>
  <%= text_field_tag :search_name, params[:search_name], :placeholder => '브랜드명', :class => 'input-large' %>
  <%= text_field_tag :search_korea_name, params[:search_korea_name], :placeholder => '브랜드한글명', :class => 'input-large' %>
  <!-- 라인업수 존재여부 -->
  <%= label_tag :search_line_up, :class => 'search-label' do %>
    <span class="search-label-title">라인업 여부</span>
    <%= select_tag :search_line_up, options_for_select([['라인업 존재', 1], ['라인업 미존재', 0]], params[:search_line_up]), :prompt => '전체', :class => 'input-medium' %>
  <% end %>
  <br />
  <%= text_field_tag :created_at_start, params[:created_at_start], :placeholder => '생성일자 시작(ex: 20130101)', :class => 'input-large' %>
  <%= text_field_tag :created_at_end, params[:created_at_end], :placeholder => '생성일자 종료(ex: 20130101)', :class => 'input-large' %>

  <%= submit_tag '검색', :class => "btn btn-default" %>
  <%= link_to '초기화', admin_test_brands_path, :class => 'btn btn-inverse' %>
<% end %>

<table class="table table-striped table-condensed">
  <tr>
    <th>DBID</th>
    <th>브랜드코드</th>
    <th>브랜드명</th>
    <th>브랜드한글명</th>
    <th>라인업 수</th>
    <th>지역</th>
    <th>Action</th>
  </tr>

  <% @test_brands.each do |test_brand| %>
    <tr>
      <td><%= test_brand.id %></td>
      <td><%= test_brand.code %></td>
      <td><%= test_brand.name %></td>
      <td><%= test_brand.korea_name %></td>
      <td><%= test_brand.linup_count %></td>
      <td><%= test_brand.country %></td>
      <td>
        <%= link_to raw("<i class=\"glyphicon glyphicon-wrench glyphicon-white\"></i>"), edit_admin_test_brand_path(test_brand), :class => "btn btn-warning" %>
        <%= link_to raw("<i class='glyphicon glyphicon-trash glyphicon-white'></i>"), admin_test_brand_path(test_brand), :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-danger" %>
      </td>
    </tr>
  <% end %>

</table>
<%= will_paginate(:previous_label => "&#171; #{t('prev')}", :next_label => "#{t('next')} &#187;", :class => "text-center") %>
<%= link_to '생성', new_admin_test_brand_path, :class => 'btn btn-primary' %>

test_crud/app/views/admin/test_brands/new.html.erb
<%= render :partial => 'breadcrumb' %>
<%= render :partial => 'form' %>